### PR TITLE
Edit task pull request

### PR DESCRIPTION
**Pull request by Angop**
added an edit task modal popup when edit>edit task is pressed. Also added put request functionality in front and backend

### CODE REVIEW

**Comment by zackrogman** [comment]
everything looks really good here! The only things are that type and date should be added into the modal, and I wonder if you should have discarded changes to files like eslintcache before merging

**Comment by doliverjr** [comment]
Add type and dat to the initial state in Modal.js just to keep consistency across all the files

**Comment by Angop** [comment]
Type and date are now added to the Modal (see New Task Popup PR). I'll get better about discarding eslintcache changes.

**Comment by Jvondamm** [comment]
Looks great! Aside from what the other two mentioned, and I'm being picky here, but maybe a little space between the submit and cancel buttons?

**Comment by Angop** [comment]
> 
> 
> Looks great! Aside from what the other two mentioned, and I'm being picky here, but maybe a little space between the submit and cancel buttons?

Okay I will look into that in the morning.

**Pull request merged**
