### PR TITLE
Checkbox

### PR DESCRIPTION
**Pull request by Jvondamm**
works on frontend and backend, and strikes through check. The checkbox UI is broken

### CODE REVIEW

**Comment by Angop** [comment]
I would recommend removing console.log() lines from debugging and any unused functions (handlePatch?). Other than that it looks great!

**Comment by zackrogman** [comment]
many lines are commented out rather than deleted, making the code more confusing/less readable

**Comment by zackrogman** [comment]
Nothing to add from what Angela said. console.log lines should be removed before pushing to the main branch as these are for debugging and handlePatch may be deleted as it is not called anywhere

**Comment by doliverjr** [comment]
I wonder if there is a way to make the strikethrough code more compact as to not have large blank spaces in the code. Strictly visual

**Comment by Jvondamm** [comment]
ok, I'll remove the console lines and look into the unneeded functions. and there is probably a way to make the code formatted better, I'll look into that for my next pr.

**Pull request merged**
